version: '3'

networks:
  sidecar:
    driver: bridge
services:
  entregadelosalpes:
    build:
      context: ./
      dockerfile: entregadelosalpes.Dockerfile
    container_name: entregadelosalpes
    hostname: entregadelosalpes
    image: entregadelosalpes 
    networks:
      - sidecar
    labels:
      SidecarDiscover: "false"
    ports:
      - "5000:5000"

  adaptador:
    build:
      context: ./
      dockerfile: adaptador.Dockerfile
    container_name: adaptador
    hostname: adaptador
    image: adaptador
    networks:
      - sidecar
    environment:
      - ENTREGADELOSALPES_ADDRESS=entregadelosalpes
    ports:
      - "50051:50051"
  
  authentication:
    build:
        context: ./
        dockerfile: auth.Dockerfile
    container_name: authentication
    hostname: authentication
    image: authentication 
    networks:
      - sidecar
    labels:
      SidecarDiscover: "false"
    ports:
      - "5002:5002"
    

  bff:
    build:
        context: ./
        dockerfile: bff.Dockerfile
    container_name: bff
    hostname: bff
    image: bff 
    networks:
      - sidecar
    labels:
      SidecarDiscover: "false"
    ports:
      - "8003:8003"

  pulsar:
    image: apachepulsar/pulsar:2.5.2
    container_name: my-pulsar
    expose:
       - 8080
       - 6650
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"



  entrega:
    build:
      context: ./
      dockerfile: entrega.Dockerfile
    ports:
      - "5001:5000"
      - "5000:5001"
    volumes:
      - .:/opt

  # MySQL8
  db:
    image: mysql:8
    hostname: mysqldb
    container_name: mysqldb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=reservas
      - MYSQL_ROOT_PASSWORD=adminadmin
    profiles: [ "aeroalpes", "db" ]
    networks:
      - sidecar
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql