# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orden.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0borden.proto\x12\x05orden\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n\x08Producto\x12\x16\n\x0e\x66\x65\x63ha_creacion\x18\x01 \x01(\t\x12\x1b\n\x13\x66\x65\x63ha_actualizacion\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\t\"\xa9\x01\n\x05Orden\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x66\x65\x63ha_creacion\x18\x02 \x01(\tH\x01\x88\x01\x01\x12 \n\x13\x66\x65\x63ha_actualizacion\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1e\n\x05items\x18\x04 \x03(\x0b\x32\x0f.orden.ProductoB\x05\n\x03_idB\x11\n\x0f_fecha_creacionB\x16\n\x14_fecha_actualizacion\"\x18\n\nQueryOrden\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x0eRespuestaOrden\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12 \n\x05orden\x18\x02 \x01(\x0b\x32\x0c.orden.OrdenH\x00\x88\x01\x01\x42\x08\n\x06_orden2|\n\x07Ordenes\x12\x33\n\nCrearOrden\x12\x0c.orden.Orden\x1a\x15.orden.RespuestaOrden\"\x00\x12<\n\x0e\x43onsultarOrden\x12\x11.orden.QueryOrden\x1a\x15.orden.RespuestaOrden\"\x00\x42.\n\x18\x63o.edu.uniandes.misw4406B\nOrdenProtoP\x01\xa2\x02\x03ORDb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orden_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030co.edu.uniandes.misw4406B\nOrdenProtoP\001\242\002\003ORD'
  _PRODUCTO._serialized_start=55
  _PRODUCTO._serialized_end=150
  _ORDEN._serialized_start=153
  _ORDEN._serialized_end=322
  _QUERYORDEN._serialized_start=324
  _QUERYORDEN._serialized_end=348
  _RESPUESTAORDEN._serialized_start=350
  _RESPUESTAORDEN._serialized_end=427
  _ORDENES._serialized_start=429
  _ORDENES._serialized_end=553
# @@protoc_insertion_point(module_scope)
